# Generated by Django 4.1.9 on 2024-01-26 05:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('Admin_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('Admin_username', models.CharField(max_length=20)),
                ('Admin_name', models.CharField(max_length=10)),
                ('Admin_pass', models.TextField(max_length=10)),
                ('Admin_email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='ArtGalleryManager',
            fields=[
                ('Manager_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('Name', models.CharField(max_length=10)),
                ('Contact_no', models.IntegerField()),
                ('Username', models.CharField(max_length=40)),
                ('Email', models.EmailField(max_length=254)),
                ('id_proof', models.ImageField(upload_to='')),
                ('password', models.TextField(max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='Artist',
            fields=[
                ('Artist_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('Artist_name', models.CharField(max_length=50)),
                ('Artist_username', models.CharField(max_length=40)),
                ('Artist_pass', models.TextField(max_length=25)),
                ('Artist_email', models.EmailField(max_length=254)),
                ('Artist_idProof', models.ImageField(upload_to='')),
                ('Artist_contact_no', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('Customer_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('Customer_name', models.CharField(max_length=10)),
                ('Customer_username', models.CharField(max_length=10)),
                ('Contact_no', models.IntegerField()),
                ('Customer_Email', models.EmailField(max_length=254)),
                ('Customer_password', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('Event_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('Event_name', models.CharField(max_length=10)),
                ('Event_time', models.TimeField()),
                ('Event_date', models.DateField()),
                ('Event_venue', models.CharField(max_length=30)),
                ('Event_capacity', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('Product_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('Name', models.CharField(max_length=30)),
                ('Description', models.CharField(max_length=50)),
                ('Weight', models.FloatField(max_length=10)),
                ('Price', models.IntegerField()),
                ('Picture', models.ImageField(upload_to='')),
                ('Artist_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Artify__core.artist')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('Order_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('OrderNo', models.IntegerField()),
                ('Order_Amount', models.IntegerField()),
                ('Order_Date', models.DateField()),
                ('Order_quantity', models.IntegerField()),
                ('Customer_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Artify__core.customer')),
                ('Product_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Artify__core.product')),
            ],
        ),
    ]
