# Generated by Django 4.1.9 on 2023-12-21 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('Admin_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('Admin_username', models.CharField(max_length=20)),
                ('Admin_name', models.CharField(max_length=10)),
                ('Admin_pass', models.TextField(max_length=10)),
                ('Admin_email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='Artist',
            fields=[
                ('Artist_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('Artist_name', models.CharField(max_length=50)),
                ('Artist_username', models.CharField(max_length=40)),
                ('Artist_pass', models.TextField(max_length=25)),
                ('Artist_email', models.EmailField(max_length=254)),
                ('Artist_idProof', models.IntegerField()),
                ('Artist_contact_no', models.IntegerField(max_length=13)),
            ],
        ),
    ]
