# Generated by Django 4.1.9 on 2023-12-21 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Artify__core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artist',
            name='Artist_contact_no',
            field=models.IntegerField(),
        ),
    ]
