# Generated by Django 4.1.9 on 2024-01-26 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Artify__core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artgallerymanager',
            name='password',
            field=models.CharField(max_length=25),
        ),
    ]
