# Generated by Django 4.1.9 on 2023-12-27 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Artify__core', '0002_alter_artist_artist_contact_no'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artist',
            name='Artist_idProof',
            field=models.ImageField(upload_to=''),
        ),
    ]
