# Generated by Django 4.1.9 on 2023-12-30 06:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Artify__core', '0003_alter_artist_artist_idproof'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArtGalleryManager',
            fields=[
                ('Manager_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('Name', models.CharField(max_length=10)),
                ('Contact_no', models.IntegerField()),
                ('Username', models.CharField(max_length=40)),
                ('Email', models.EmailField(max_length=254)),
                ('id_proof', models.ImageField(upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('Customer_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('Customer_name', models.CharField(max_length=10)),
                ('Contact_no', models.IntegerField()),
                ('Customer_Email', models.EmailField(max_length=254)),
                ('Customer_idProof', models.ImageField(upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('Event_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('Event_name', models.CharField(max_length=10)),
                ('Event_time', models.TimeField()),
                ('Event_date', models.DateField()),
                ('Event_venue', models.CharField(max_length=30)),
                ('Event_capacity', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('Product_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('Name', models.CharField(max_length=30)),
                ('Description', models.CharField(max_length=50)),
                ('Weight', models.FloatField(max_length=10)),
                ('Price', models.IntegerField()),
                ('Picture', models.ImageField(upload_to='')),
                ('Artist_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Artify__core.artist')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('Order_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('OrderNo', models.IntegerField()),
                ('Order_Amount', models.IntegerField()),
                ('Order_Date', models.DateField()),
                ('Order_quantity', models.IntegerField()),
                ('Customer_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Artify__core.customer')),
                ('Product_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Artify__core.product')),
            ],
        ),
    ]
